### ISSUE TITLE
As a staff I can filter adopter applications by pet name, applicant name, application status

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#355] opened 2023-12-02 00:56 UTC
Look at the filter used on the Pet Index page for an idea how to handle it and how it should function and look. 

Acceptance criteria
- staff can filter adopter applications by pet name, applicant name, application status

**Comment by phonghpham** [comment] 2023-12-02 02:19
@kasugaijin, I'm down for the cause. Please assign this to me!

**Comment by kasugaijin** [comment] 2023-12-02 03:00
All yours @phonghpham

**Closed** 2023-12-22 03:05 UTC
