### ISSUE TITLE
Organization edit 'About Us' section

### ISSUE THREAD

**Issue by jadekstewart3** [rubyforgood/pet-rescue#166] opened 2023-09-05 19:18 UTC
As an organization admin, when I visit "slug/organization_profile/edit".
- On the edit organization page I see an "About Us" field.
- When I enter text into the "About Us" field, and click "Update", I can see that the "About Us" section of my organization has been updated.

[Figma](https://www.figma.com/file/4PqQX8NeOVE9ca2GT4Xz76/Pet-Rescue?type=design&node-id=10-4&mode=design&t=rkMfXskGSM7Tivas-4)

**Comment by LittleBigProgramming** [comment] 2023-10-07 12:19
Hey :) I would like to work on this if it's available?

**Comment by DreamVenerable** [comment] 2023-12-26 15:50
Can I take this issue?

**Comment by veezus** [comment] 2024-02-10 16:45
I'm interested in picking this issue up. Is it still available?

**Comment by nsiwnf** [comment] 2024-03-18 04:22
Duplicate of #480

**Closed by nsiwnf** 2024-03-18 04:22 UTC
